### ISSUE TITLE
wait signal timeout: b'login: '

### ISSUE THREAD

**Issue by bobleeSwagger2** [offspot/kiwix-hotspot#642]
I have tried multiple times unsuccessfully to install the hotspot (via windows exe). I tried first with the latest release 2.4.11 and even downloaded as far back as 2.4.7 to see if it was something recently introduced but all are the same. Here is the last text I'm seeing upon each failed install-
--- Exception Trace --- 
Traceback (most recent call last): 
File "run_installation.py", line 296, in run_installation 
File "backend\qemu.py", line 160, in __enter__ 
File "backend\qemu.py", line 264, in _boot 
File "backend\qemu.py", line 208, in _wait_signal 
backend.qemu.QemuException: wait signal timeout: b'login: '
--- 
[8:00:50 PM] Restoring system sleep policy 
[8:00:50 PM] Restoring ES_CONTINUOUS mode to current thread 
[8:00:50 PM] *** DURATIONS SUMMARY *** 
[8:00:50 PM] [1/5] Retrieve Master Image: 20 minutes and 16.25 seconds (3/16/2022 7:25:52 PM to 3/16/2022 7:46:09 PM) 
[8:00:50 PM] [2/5] Download contents: 3 minutes and 12.18 seconds (3/16/2022 7:46:09 PM to 3/16/2022 7:49:21 PM) 
[8:00:50 PM] TOTAL: 34 minutes and 57.74 seconds (3/16/2022 7:25:52 PM to 3/16/2022 8:00:50 PM) 
[8:00:50 PM] --> Failed: wait signal timeout: b'login: ' 
[8:00:50 PM] Installation failed: wait signal timeout: b'login: ' 
[8:00:50 PM] [STAGE 3/5: Image configuration (virtualized) - 60%]
I hope this helps! I want to get this on my RPI4 but can't even get to the point of having an image file to flash on my card.

**Comment by rgaudin** [comment]
Can you give some details on your computer? Windows version and hardware. Also, please include the full log so we can assess what's going on. From what you shared, the virtual system could fail to boot or be too slow or the connection between the installer and the virtual system could be the problem.

**Comment by kelson42** [comment]
No feedback. Closing the ticket.
