### ISSUE TITLE
KIWIX hotspot failed during virtualization

### ISSUE THREAD

**Issue by skullboneslayer** [offspot/kiwix-hotspot#689]
I am having some issues when trying to make a hotspot for my Raspberry Pi using the installer. After downloading all my chosen and selected data, it fails during the virtualization stage. Note, I had over 100GB of data after the expected 256 GB needed. Any idea how I can fix this issue? The log files for the fail are below:

[11:22:42 AM] [STAGE 3/6: Image configuration (virtualized) - 33%]
[11:22:42 AM] --> Preparing qemu VM
[11:22:42 AM]  using 2 GiB RAM
[11:22:42 AM] Call: ['C:\\Users\\mattt\\AppData\\Local\\Temp\\7zSFDAB.tmp\\qemu\\qemu-img.exe', 'info', '-f', 'raw', 'C:\\hotspot-2023_10_25-09_54_32.BUILDING.img']
[11:22:42 AM] image: C:\hotspot-2023_10_25-09_54_32.BUILDING.img
[11:22:42 AM] file format: raw
[11:22:42 AM] virtual size: 8 GiB (8589934592 bytes)
[11:22:42 AM] disk size: 8 GiB
[11:22:42 AM] --> Resizing image file from 8 GiB to 256 GiB
[11:22:42 AM] Call: ['C:\\Users\\mattt\\AppData\\Local\\Temp\\7zSFDAB.tmp\\qemu\\qemu-img.exe', 'info', '-f', 'raw', 'C:\\hotspot-2023_10_25-09_54_32.BUILDING.img']
[11:22:42 AM] image: C:\hotspot-2023_10_25-09_54_32.BUILDING.img
[11:22:42 AM] file format: raw
[11:22:42 AM] virtual size: 8 GiB (8589934592 bytes)
[11:22:42 AM] disk size: 8 GiB
[11:22:42 AM] Call: ['C:\\Users\\mattt\\AppData\\Local\\Temp\\7zSFDAB.tmp\\qemu\\qemu-img.exe', 'resize', '-f', 'raw', 'C:\\hotspot-2023_10_25-09_54_32.BUILDING.img', '274877906944']
[11:22:42 AM] C:\Users\mattt\AppData\Local\Temp\7zSFDAB.tmp\qemu\qemu-img.exe: SetEndOfFile error: There is not enough space on the disk.
[11:22:42 AM] 
--- Exception Trace ---
Traceback (most recent call last):
  File "run_installation.py", line 292, in run_installation
  File "backend\qemu.py", line 138, in resize_image
  File "backend\util.py", line 104, in subprocess_pretty_check_call
  File "backend\util.py", line 97, in subprocess_pretty_call
backend.util.CheckCallException: Process ['C:\\Users\\mattt\\AppData\\Local\\Temp\\7zSFDAB.tmp\\qemu\\qemu-img.exe', 'resize', '-f', 'raw', 'C:\\hotspot-2023_10_25-09_54_32.BUILDING.img', '274877906944'] failed

---
[11:22:42 AM] --> Failed: Process ['C:\\Users\\mattt\\AppData\\Local\\Temp\\
[11:22:42 AM] Installation failed: Process ['C:\\Users\\mattt\\AppData\\Local\\Temp\\7zSFDAB.tmp\\qemu\\qemu-img.exe', 'resize', '-f', 'raw', 'C:\\hotspot-2023_10_25-09_54_32.BUILDING.img', '274877906944'] failed
[11:22:42 AM] [STAGE 3/6: Image configuration (virtualized) - 50%]
[11:22:42 AM] Restoring system sleep policy
[11:22:42 AM] Restoring ES_CONTINUOUS mode to current thread
[11:22:42 AM] *** DURATIONS SUMMARY ***
[11:22:42 AM] [1/6] Retrieve Master Image: 1 minute and 11.64 seconds (10/25/2023 9:54:32 AM to 10/25/2023 9:55:44 AM)
[11:22:42 AM] [2/6] Download contents: 1 hour, 26 minutes and 58.16 seconds (10/25/2023 9:55:44 AM to 10/25/2023 11:22:42 AM)
[11:22:42 AM] [3/6] Image configuration (virtualized): 0.47 seconds (10/25/2023 11:22:42 AM to 10/25/2023 11:22:42 AM)
[11:22:42 AM] TOTAL: 1 hour, 28 minutes and 10.28 seconds (10/25/2023 9:54:32 AM to 10/25/2023 11:22:42 AM)

**Comment by skullboneslayer** [comment]
Update fix and new issue, I required double the size on my local drive, so for my 256 GB SD card, I needed 512 GB on my computer and that fixed the issue. However, now I have a new issue where DHCPCD fails to initiate, and although the Wifi Hotspot comes on and I can connect and get to the home screen, when I click on any of the included material, for example WIkipedia, it says Not found on server.

**Comment by rgaudin** [comment]
OK, Can you please share the Pi you're using, the config if you got a chance to export it and the software you used to write the file to the SD card? We recommend the rasberrypi imager GUI…letting it do it's post-writing check. This ensures the SD card still works properly.

**Comment by skullboneslayer** [comment]
For sure, I am using a Raspberry Pi 4B (4GB version). To write the SD card, the first time I used the installer itself and it wrote the SD card, the second time I took the generated ISO and used Etcher with the same result. I attached the Config file from the Pi, let me know if this is the wrong one, I am still learning Raspberry Pi's 😅 
[config.txt](https://github.com/offspot/kiwix-hotspot/files/13189434/config.txt)

**Comment by kelson42** [comment]
Unfortunately this product has been discontinued. Therefore this issue won't be fixed/implemented. A bit more details can be found [here](https://github.com/offspot/kiwix-hotspot/blob/main/README.md).
